export default [
    {
        img: "/images/beignoir.jpg",
        title: "Beignoir",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab eius molestias, quasi, quam omnis magnam impedit hic totam repudiandae reiciendis voluptate inventore nisi quidem.",
        price: "",
        postdate:"",
    },
    {
        img: "/images/canape.jpg",
        title: "Canapé",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab eius molestias, quasi, quam omnis magnam impedit hic totam repudiandae reiciendis voluptate inventore nisi quidem.",
        price: "",
        postdate:"",
    },
    {
        img: "/images/tableAmanger.jpg",
        title: "Table à manger",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab eius molestias, quasi, quam omnis magnam impedit hic totam repudiandae reiciendis voluptate inventore nisi quidem.",
        price: "",
        postdate:"",
    },
    {
        img: "/images/pioupiou.jpg",
        title: "Fauteuil pioupiou",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab eius molestias, quasi, quam omnis magnam impedit hic totam repudiandae reiciendis voluptate inventore nisi quidem.",
        price: "",
        postdate:"",
    },
    {
        img: "/images/reveil.jpg",
        title: "Réveil",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab eius molestias, quasi, quam omnis magnam impedit hic totam repudiandae reiciendis voluptate inventore nisi quidem.",
        price: "",
        postdate:"",
    },
    {
        img: "/images/lit.jpg",
        title: "Lit",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab eius molestias, quasi, quam omnis magnam impedit hic totam repudiandae reiciendis voluptate inventore nisi quidem.",
        price: "",
        postdate:"",
    },
    {
        img: "/images/coiffeuse.jpg",
        title: "Coiffeuse",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab eius molestias, quasi, quam omnis magnam impedit hic totam repudiandae reiciendis voluptate inventore nisi quidem.",
        price: "",
        postdate:"",
    },
    {
        img: "/images/salon.jpg",
        title: "Salon",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab eius molestias, quasi, quam omnis magnam impedit hic totam repudiandae reiciendis voluptate inventore nisi quidem.",
        price: "",
        postdate:"",
    },
    {
        img: "/images/chaise.jpg",
        title: "Chaise",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab eius molestias, quasi, quam omnis magnam impedit hic totam repudiandae reiciendis voluptate inventore nisi quidem.",
        price: "",
        postdate:"",
    },
    {
        img: "/images/glassCabinet.jpg",
        title: "Glass cabinet",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab eius molestias, quasi, quam omnis magnam impedit hic totam repudiandae reiciendis voluptate inventore nisi quidem.",
        price: "",
        postdate:"",
    },
    {
        img: "/images/tableDeChevet.jpg",
        title: "Table de chevet",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab eius molestias, quasi, quam omnis magnam impedit hic totam repudiandae reiciendis voluptate inventore nisi quidem.",
        price: "",
        postdate:"",
    },
    {
        img: "/images/bookShelf.jpg",
        title: "Bookshelf",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab eius molestias, quasi, quam omnis magnam impedit hic totam repudiandae reiciendis voluptate inventore nisi quidem.",
        price: "",
        postdate:"",
    },
    {
        img: "/images/lampe.jpg",
        title: "Lampe",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab eius molestias, quasi, quam omnis magnam impedit hic totam repudiandae reiciendis voluptate inventore nisi quidem.",
        price: "",
        postdate:"",
    },
    {
        img: "/images/tissueBox.jpg",
        title: "Tissue Box",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab eius molestias, quasi, quam omnis magnam impedit hic totam repudiandae reiciendis voluptate inventore nisi quidem.",
        price: "",
        postdate:"",
    },
    {
        img: "/images/miroir.jpg",
        title: "Miroir",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab eius molestias, quasi, quam omnis magnam impedit hic totam repudiandae reiciendis voluptate inventore nisi quidem.",
        price: "",
        postdate:"",
    },
    {
        img: "/images/chaiseBureau.jpg",
        title: "Chaise et bureau",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab eius molestias, quasi, quam omnis magnam impedit hic totam repudiandae reiciendis voluptate inventore nisi quidem.",
        price: "",
        postdate:"",
    },
    {
        img: "/images/bibliotheque.jpg",
        title: "Bibliothèque",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab eius molestias, quasi, quam omnis magnam impedit hic totam repudiandae reiciendis voluptate inventore nisi quidem.",
        price: "",
        postdate:"",
    },
    {
        img: "/images/tableBasse.jpg",
        title: "Table basse",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab eius molestias, quasi, quam omnis magnam impedit hic totam repudiandae reiciendis voluptate inventore nisi quidem.",
        price: "",
        postdate:"",
    },
    
]